apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.fullname" . }}-secondary
  labels:
    {{- include "adguard.resolver.podLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: web
  selector:
    {{- include "adguard.resolver.selectorLabels" . | nindent 4 }}
