apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "common.fullname" . }}-secondary
  labels:
    app.kubernetes.io/name: {{ template "common.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "adguard-secondary"
    {{- include "common.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: 0
  replicas: {{ .Values.secondary.replicas }}
  serviceName: {{ template "common.fullname" . }}-secondary
  selector:
    matchLabels:
      app.kubernetes.io/component: "adguard-secondary"
      {{- include "common.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: "adguard-secondary"
        {{- include "common.selectorLabels" . | nindent 8 }}
    spec:
      priorityClassName: {{ .Values.secondary.priorityClassName }}
      {{- with .Values.secondary.topologySpreadConstraints }}
      topologySpreadConstraints: {{ . |toYaml | nindent 8 }}
      {{- end }}
      tolerations: {{ toYaml .Values.secondary.tolerations | nindent 8 }}
      containers:
        - name: adguard
          image: "{{ .Values.global.image.registry }}/{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: "Europe/Amsterdam"
            - name: ADGUARD_HOME_DEFAULT_WEB_PORT
              value: "3000"
          args:
            - --config
            - /opt/adguardhome/conf/AdGuardHome.yaml
            - --work-dir
            - /opt/adguardhome/work
            - --no-check-update
          readinessProbe:
            httpGet:
              port: web
              path: /
          ports:
            - name: web
              containerPort: 3000
              protocol: TCP
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
          resources: {{ toYaml .Values.secondary.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /opt/adguardhome/conf
              subPath: conf
            - name: data
              mountPath: /opt/adguardhome/work
              subPath: work
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app.kubernetes.io/name: {{ template "common.name" . }}
          app.kubernetes.io/instance: {{ .Release.Name }}
          app.kubernetes.io/component: "adguard-secondary"
          {{- if .Values.global.persistence.labels }}
          {{ toYaml .Values.global.persistence.labels | nindent 10 }}
          {{- end}}
          {{- if .Values.secondary.persistence.labels }}
          {{ toYaml .Values.secondary.persistence.labels | nindent 10 }}
          {{- end}}
      spec:
        {{- if hasKey .Values.secondary.persistence "storageClass" }}
        storageClassName: {{ .Values.secondary.persistence.storageClass | quote }}
        {{- else if hasKey .Values.global.persistence "storageClass" }}
        storageClassName: {{ .Values.global.persistence.storageClass | quote }}
        {{- end }}
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.secondary.persistence.size | default .Values.global.persistence.size }}
