apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: app
  labels:
    {{- include "immich.database.podLabels" . | nindent 4 }}
spec:
  name: app
  owner: app
  cluster:
    name: {{ .Values.database.clusterName }}
  extensions:
  - name: vectors
    ensure: absent
  - name: vector
    ensure: present
  - name: vchord
    ensure: present
    version: 0.4.2
  - name: earthdistance
    ensure: present
