apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.database.clusterName }}
  labels:
    app.kubernetes.io/component: "db"
    {{- include "common.labels" . | nindent 4 }}
spec:
  instances: {{ .Values.database.replicas }}
  imageName: {{ .Values.database.image.registry }}/{{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}

  postgresql:
    shared_preload_libraries:
      - "vectors.so"

  logLevel: {{ .Values.database.logLevel }}

  bootstrap:
    initdb:
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS "vectors";
        - CREATE EXTENSION IF NOT EXISTS "cube";
        - CREATE EXTENSION IF NOT EXISTS "earthdistance";
        - ALTER SYSTEM SET search_path TO app, public, vectors;
        - ALTER SCHEMA vectors OWNER TO app;
        # run this via kubectl exec in database pod after the schema is created
        #- \c app; GRANT SELECT ON TABLE pg_vector_index_stat TO app;

  storage:
    size: {{ .Values.database.size }}

  {{ if .Values.database.backups.enabled }}
  backup:
    retentionPolicy: {{ .Values.database.backups.retention }}
    barmanObjectStore:
      destinationPath: {{ .Values.database.backups.path | quote }}
      endpointURL: {{ .Values.database.backups.endpoint }}
      s3Credentials:
        accessKeyId:
          name: {{ .Values.database.backups.secretName }}
          key: ACCESS_KEY
        secretAccessKey:
          name: {{ .Values.database.backups.secretName }}
          key: SECRET_KEY
  {{ end }}

  {{- if .Values.database.topologySpreadConstraints }}
  topologySpreadConstraints:
  {{- range .Values.database.topologySpreadConstraints }}
  - maxSkew: 1
    topologyKey: {{ .topologyKey }}
    whenUnsatisfiable: {{ .whenUnsatisfiable }}
    labelSelector:
      matchLabels:
        "cnpg.io/cluster": {{ .Values.database.clusterName }}
  {{- end }}
  {{- end }}