{{- if .Values.database.backups.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: {{ .Values.database.clusterName }}
spec:
  cluster:
    name: {{ .Values.database.clusterName }}
  schedule: {{ .Values.database.backups.schedule | quote }}
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
    parameters:
      retentionPolicy: {{ .Values.database.backups.scheduledBackupRetention | quote }}
{{- end }}
