apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "common.fullname" . }}-primary
  labels:
    app.kubernetes.io/name: {{ template "common.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "adguard-primary"
    {{- include "common.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: 0
  replicas: 1
  strategy: 
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "common.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: "adguard-primary"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "common.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: "adguard-primary"
        {{- include "common.labels" . | nindent 8 }}
    spec:
      initContainers:
        - name: sync
          image: "{{ .Values.primary.sync.image.registry }}/{{ .Values.primary.sync.image.repository }}:{{ .Values.primary.sync.image.tag }}"
          imagePullPolicy: IfNotPresent
          restartPolicy: Always
          readinessProbe:
            httpGet:
              port: sync
              path: /healthz
          livenessProbe:
            httpGet:
              port: sync
              path: /healthz
          args:
            - run
          env:
            - name: ORIGIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.primary.secretName }}
                  key: password
          {{- range $i, $v := untilStep 1 ((add1 .Values.secondary.replicas) | int ) 1 }}
            - name: REPLICA{{ $v }}_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "common.fullname" $ }}-secondary-password
                  key: password
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ template "common.fullname" . }}-sync-config
          ports:
            - name: sync
              containerPort: 8080
              protocol: TCP
          resources: {{ toYaml .Values.primary.sync.resources | nindent 12 }}
      containers:
        - name: adguard
          image: "{{ .Values.global.image.registry }}/{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: "Europe/Amsterdam"
          args:
            - --config
            - /opt/adguardhome/conf/AdGuardHome.yaml
            - --work-dir
            - /opt/adguardhome/work
            - --no-check-update
          readinessProbe:
            httpGet:
              port: web
              path: /
          ports:
            - name: web
              containerPort: 3000
              protocol: TCP
          resources: {{ toYaml .Values.primary.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /opt/adguardhome/conf
              subPath: conf
            - name: data
              mountPath: /opt/adguardhome/work
              subPath: work
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ template "common.fullname" . }}-primary
