{{ if .Values.primary.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "common.fullname" . }}
  annotations: {{ toYaml .Values.primary.ingress.annotations | nindent 4 }}
  labels:
    app.kubernetes.io/name: {{ template "common.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "adguard"
    {{- include "common.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.primary.ingress.class }}
  rules:
    - host: {{ .Values.primary.ingress.domain }}
      http:
        paths:
          - backend:
              service:
                name:  {{ template "common.fullname" . }}-web
                port:
                  number: 3000
            path: /
            pathType: Prefix
  {{- if .Values.primary.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.primary.ingress.domain }}
      secretName: {{ .Values.primary.ingress.tls.secretName }}
  {{- end }}
{{ end }}
