apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "common.fullname" . }}-primary
  labels:
    app.kubernetes.io/name: {{ template "common.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "adguard-primary"
    {{- include "common.labels" . | nindent 4 }}
    {{- if .Values.adguard.persistence.labels }}
    {{ toYaml .Values.adguard.persistence.labels | nindent 4 }}
    {{- end}}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.primary.persistence.existingVolume }}
  volumeName: {{ .Values.primary.persistence.existingVolume }}
  storageClassName: ""
  {{- else }}
  {{- if hasKey .Values.primary.persistence "storageClass" }}
  storageClassName: {{ .Values.primary.persistence.storageClass | quote }}
  {{- else if hasKey .Values.adguard.persistence "storageClass" }}
  storageClassName: {{ .Values.adguard.persistence.storageClass | quote }}
  {{- end }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.primary.persistence.size | default .Values.adguard.persistence.size }}
