apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "common.fullname" . }}-primary
  labels:
    app.kubernetes.io/name: {{ template "common.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "adguard-primary"
    {{- include "common.labels" . | nindent 4 }}
    {{ if .Values.persistence.labels }}
    {{ toYaml .Values.persistence.labels | nindent 4 }}
    {{ end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
