apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.fullname" . }}-web
  labels:
    {{- include "adguard.frontend.podLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: web
  selector:
    {{- include "adguard.frontend.selectorLabels" . | nindent 4 }}
