apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {s{ template "common.fullname" . }}-library
  labels:
    app.kubernetes.io/name: {{ template "common.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "immich"
    {{- include "common.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if hasKey .Values.persistence "storageClass" }}
  {{- with .Values.persistence.storageClass }}
  storageClassName: {{ . }}
  {{- else }}
  storageClassName: ""
  {{- end }}
  {{- end }}
  {{- with .Values.persistence.existingVolume }}
  volumeName: {{ . }}
  {{- end}}
