apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "common.fullname" . }}-library
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/component: library
    helm.sh/chart: {{ include "chartName" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: immich
    {{- if .Values.persistence.labels }}
    {{ toYaml .Values.persistence.labels | nindent 4 }}
    {{- end}}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if hasKey .Values.persistence "storageClass" }}
  {{- with .Values.persistence.storageClass }}
  storageClassName: {{ . }}
  {{- else }}
  storageClassName: ""
  {{- end }}
  {{- end }}
  {{- with .Values.persistence.existingVolume }}
  volumeName: {{ . }}
  {{- end}}
