apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "common.fullname" . }}-library
  labels:
    {{- include "immich.library.labels" . | nindent 4 }}
    {{- if .Values.persistence.labels }}
    {{ toYaml .Values.persistence.labels | nindent 4 }}
    {{- end}}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if hasKey .Values.persistence "storageClass" }}
  {{- with .Values.persistence.storageClass }}
  storageClassName: {{ . }}
  {{- else }}
  storageClassName: ""
  {{- end }}
  {{- end }}
  {{- with .Values.persistence.existingVolume }}
  volumeName: {{ . }}
  {{- end}}
