apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.fullname" . }}-server-metrics
  labels:
    {{- include "immich.api.podLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: server-metrics
      port: 8081
      targetPort: server-metrics
    - name: jobs-metrics
      port: 8082
      targetPort: jobs-metrics
  selector:
      app.kubernetes.io/component: "server"
      {{- include "common.selectorLabels" . | nindent 6 }}
