apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "common.fullname" . }}-server
  labels:
    app.kubernetes.io/component: "server"
    {{- include "common.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: "server"
      {{- include "common.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: server-metrics
      scheme: http
    - port: jobs-metrics
      scheme: http
