apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "common.fullname" . }}-server
  labels:
    {{- include "immich.api.podLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "immich.api.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: server-metrics
      scheme: http
    - port: jobs-metrics
      scheme: http
