apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.fullname" . }}
  labels:
    app.kubernetes.io/component: "server"
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 2283
      targetPort: http
  selector:
    app.kubernetes.io/component: "server"
    {{- include "common.selectorLabels" . | nindent 4 }}
