apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.fullname" . }}
  labels:
    {{- include "immich.api.podLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 2283
      targetPort: http
  selector:
    {{- include "immich.api.selectorLabels" . | nindent 4 }}
