apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.fullname" . }}-server-metrics
  labels:
    app.kubernetes.io/component: "server"
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: api-metrics
      port: 8081
      targetPort: api-metrics
    - name: microservices-metrics
      port: 8082
      targetPort: microservices-metrics
  selector:
      app.kubernetes.io/component: "server"
      {{- include "common.selectorLabels" . | nindent 6 }}
