{{- if .Values.photon.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.fullname" . }}-photon-loadbalancer
  labels:
    app.kubernetes.io/component: "photon-loadbalancer"
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: http
  - name: admin
    port: 9901
    targetPort: admin
  selector:
    app.kubernetes.io/component: "photon-loadbalancer"
    {{- include "common.selectorLabels" . | nindent 4 }}
{{- end }}