apiVersion: v2
name: dawarich
version: 3.1.1

home: https://dawarich.app/
sources:
- https://github.com/Freika/dawarich

dependencies:
- name: redis
  version: 21.2.6
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
