replicas: 1

nodeSelector: {}

resources: {}
#  requests:
#    memory: 512Mi
#    cpu: 100m
#  limits:
#    memory: 2048Mi

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  runAsNonRoot: true

securityContext:
  capabilities:
    drop: [ "ALL" ]
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  privileged: false

image:
  registry: ghcr.io
  repository: k8s-at-our-homes/cyberchef
  tag: 10.19.4
  digest: sha256:b9c91f30bbfa782fc90e6662d72beae262aea9e43c43c86c3bf806cc268e92f1
  pullPolicy: IfNotPresent

route:
  enabled: false
  apiVersion: gateway.networking.k8s.io/v1
  kind: HTTPRoute
  annotations: {}
  hostnames:
    - cyberchef.example.com
  parentRefs: []
  filters: []
  matches: []
  timeouts: {}

ingress:
  enabled: true
  domain: cyberchef.example.com
  class:
  annotations: {}
  tls:
    enabled: true
    secretName:
