replicas: 1

nodeSelector: {}

resources: {}
#  requests:
#    memory: 512Mi
#    cpu: 100m
#  limits:
#    memory: 2048Mi

podSecurityContext:
  runAsUser: 0
  runAsNonRoot: false # Bind to port 80 requires root

securityContext:
  capabilities:
    drop: [ "ALL" ]
    add: [ "NET_BIND_SERVICE" ]
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  privileged: false

image:
  registry: ghcr.io
  repository: gchq/cyberchef
  tag: 10.18.9
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  domain: cyberchef.example.com
  class:
  annotations: {}
  tls:
    enabled: true
    secretName:
