apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.fullname" . }}-base-config
  labels:
    {{- include "common.labels" . | nindent 4 }}
    gatus-configfile: "1"
data:
  base-config.yaml: |-
    {{ .Values.gatus.config | toYaml | nindent 4 }}
