kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "common.fullname" . }}-cluster-role-binding
  labels:
    {{- include "common.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  name: {{ template "common.fullname" . }}-cluster-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: gatus
    namespace: {{ .Release.Namespace }}
