apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.fullname" . }}-machine-learning
  labels:
    {{- include "immich.worker.podLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3003
      targetPort: http
  selector:
    {{- include "immich.worker.selectorLabels" . | nindent 4 }}
