apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.fullname" . }}-machine-learning
  labels:
    app.kubernetes.io/component: "machine-learning"
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3003
      targetPort: http
  selector:
    app.kubernetes.io/component: "machine-learning"
    {{- include "common.selectorLabels" . | nindent 4 }}
