{{- if .Values.photon.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.fullname" . }}-photon
  labels:
    {{- include "dawarich.database.podLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 2322
    targetPort: http
  selector:
    {{- include "dawarich.database.selectorLabels" . | nindent 4 }}
{{- end }}
