{{- if .Values.photon.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.fullname" . }}-photon
  labels:
    app.kubernetes.io/component: "photon"
    {{- include "component.labels" (dict "componentName" "photon" "imageTag" .Values.photon.image.tag "ctx" .) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 2322
    targetPort: http
  selector:
    app.kubernetes.io/component: "photon"
    {{- include "component.selectorLabels" (dict "componentName" "photon" "ctx" .) | nindent 4 }}
{{- end }}
