{{- if .Values.photon.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.fullname" . }}-photon
  labels:
    app.kubernetes.io/component: "photon"
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 2322
    targetPort: http
  selector:
    app.kubernetes.io/component: "photon"
    {{- include "common.selectorLabels" . | nindent 4 }}
{{- end }}
