{{- if .Values.photon.enabled }}
{{- $internalHost := dict "host" (printf "%s-photon" (include "common.fullname" .)) "scheme" "http" "port" 2322 "internal" true }}
{{- $regularHosts := list }}
{{- range $host := .Values.photon.gateway.hosts }}
{{- $processedHost := dict "host" $host.host }}
{{- if $host.rateLimit }}
{{- $processedHost = set $processedHost "rateLimit" $host.rateLimit }}
{{- end }}
{{- $processedHost = set $processedHost "scheme" "https" }}
{{- $processedHost = set $processedHost "port" 443 }}
{{- $regularHosts = append $regularHosts $processedHost }}
{{- end }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.fullname" . }}-photon-gateway-config
  labels:
    {{- include "dawarich.photonGateway.podLabels" . | nindent 4 }}
data:
  envoy.yaml: |
    admin:
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 9901
    static_resources:
      listeners:
      - name: listener_http
        address:
          socket_address:
            protocol: TCP
            address: 0.0.0.0
            port_value: 8080
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: photon
              internal_address_config:
                cidr_ranges:
                - address_prefix: {{ .Values.photon.gateway.allowedPodCidr | splitList "/" | first }}
                  prefix_len: {{ .Values.photon.gateway.allowedPodCidr | splitList "/" | last }}
              access_log:
              - name: envoy.access_loggers.stdout
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
              http_filters:
              - name: envoy.filters.http.lua
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
                  default_source_code:
                    inline_string: | {{ .Files.Get "lua/photon-response-validator.lua" | nindent 22 }}
              - name: envoy.filters.http.router
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
              route_config:
                name: photon
                virtual_hosts:
                - name: photon
                  domains: ["*"]
                  request_headers_to_remove: ["x-photon-external"]
                  response_headers_to_remove: ["x-photon-external"]
                  include_request_attempt_count: true
                  routes:
                  # Health check endpoint - direct response
                  - match:
                      path: "/healthz"
                    direct_response:
                      status: 200
                      body:
                        inline_string: "OK"
                  # If photon internal host is enabled this route is used on retry
                  - match:
                      prefix: "/"
                      headers:
                      - name: "x-photon-external"
                        present_match: true
                    route:
                      auto_host_rewrite: true
                      weighted_clusters:
                        clusters:
                        {{- range $host := $regularHosts }}
                        - name: photon_external_{{ $host.host }}
                          weight: {{ max 1 (min 100 ($host.rateLimit | default 100)) }}
                        {{- end }}
                      timeout: 30s
                      retry_policy:
                        retry_on: 5xx,gateway-error,connect-failure,refused-stream,retriable-status-codes
                        retriable_status_codes: [429]
                        num_retries: {{ len $regularHosts }}
                        per_try_timeout: 10s
                        retry_back_off:
                          base_interval: 1s
                          max_interval: 10s
                        retry_host_predicate:
                        - name: envoy.retry_host_predicates.previous_hosts
                          typed_config: 
                            "@type": type.googleapis.com/envoy.extensions.retry.host.previous_hosts.v3.PreviousHostsPredicate
                        host_selection_retry_max_attempts: {{ len $regularHosts }}
                  {{- if .Values.photon.deploy }}
                  # If photon internal host is enabled this route is used on first try
                  - match:
                      prefix: "/"
                    route:
                      weighted_clusters:
                        clusters:
                        - name: photon_internal
                          weight: 100
                      timeout: 30s
                      retry_policy:
                        retry_on: 5xx,gateway-error,connect-failure,refused-stream,retriable-status-codes
                        retriable_status_codes: [429]
                        num_retries: 50
                        per_try_timeout: 10s
                        retry_back_off:
                          base_interval: 1s
                          max_interval: 60s
                  {{- end }}
      clusters:
      {{- if .Values.photon.deploy }}
      - name: photon_internal
        connect_timeout: 2s
        per_connection_buffer_limit_bytes: 32768
        type: STRICT_DNS
        dns_lookup_family: V4_PREFERRED
        lb_policy: ROUND_ROBIN
        upstream_connection_options:
          tcp_keepalive:
            keepalive_probes: 3
            keepalive_time: 30
            keepalive_interval: 5
        circuit_breakers:
          thresholds:
          - priority: DEFAULT
            max_retries: 3
            max_connections: 50
            max_pending_requests: 50
            max_requests: 100
        outlier_detection:
          consecutive_5xx: 3
          consecutive_gateway_failure: 3
          interval: 30s
          base_ejection_time: 30s
          max_ejection_percent: 50
          split_external_local_origin_errors: true
        load_assignment:
          cluster_name: photon_internal
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: {{ $internalHost.host }}
                    port_value: {{ $internalHost.port }}
        health_checks:
        - http_health_check:
            path: /api?q=thisisahealthcheck
            expected_statuses:
            - start: 200
              end: 299
          unhealthy_threshold: 3
          healthy_threshold: 2
          timeout: 1s
          interval: 10s
      {{- end }}
      {{- range $host := $regularHosts }}
      - name: photon_external_{{ $host.host }}
        connect_timeout: 2s
        per_connection_buffer_limit_bytes: 32768
        type: STRICT_DNS
        dns_lookup_family: V4_ONLY
        lb_policy: ROUND_ROBIN
        upstream_connection_options:
          tcp_keepalive:
            keepalive_probes: 3
            keepalive_time: 30
            keepalive_interval: 5
        circuit_breakers:
          thresholds:
          - priority: DEFAULT
            max_connections: 10
            max_requests: 10
            max_pending_requests: 10
            max_retries: 2
        outlier_detection:
          consecutive_5xx: 3
          consecutive_gateway_failure: 3
          interval: 30s
          base_ejection_time: 30s
          max_ejection_percent: 50
          split_external_local_origin_errors: true
        transport_socket:
          name: envoy.transport_sockets.tls
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
            sni: {{ $host.host }}
            common_tls_context:
              validation_context:
                match_typed_subject_alt_names:
                - san_type: DNS
                  matcher:
                    exact: {{ $host.host }}
                trusted_ca:
                  filename: /etc/ssl/certs/ca-certificates.crt
        load_assignment:
          cluster_name: photon_external_{{ $host.host }}
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: {{ $host.host }}
                    port_value: {{ $host.port }}
        health_checks:
        - http_health_check:
            host: {{ $host.host }}
            path: /api?q=thisisahealthcheck
            expected_statuses:
            - start: 200
              end: 299
          unhealthy_threshold: 3
          healthy_threshold: 2
          timeout: 5s
          interval: 60s
          no_traffic_interval: 86400s
          no_traffic_healthy_interval: 604800s
      {{- end }}
{{- end }}