{{- if .Values.photon.enabled }}
{{- $allHosts := list }}
{{- $preferredHosts := list }}
{{- $regularHosts := list }}

{{- /* Add internal photon host if deployed */ -}}
{{- if .Values.photon.deploy }}
{{- $internalHost := dict "host" (printf "%s-photon" (include "common.fullname" .)) "scheme" "http" "port" 2322 "preferred" true "internal" true }}
{{- $preferredHosts = append $preferredHosts $internalHost }}
{{- end }}

{{- /* Separate hosts by preference, applying defaults */ -}}
{{- range $host := .Values.photon.gateway.hosts }}
{{- $processedHost := dict "host" $host.host }}
{{- $processedHost = set $processedHost "scheme" (default "https" $host.scheme) }}
{{- $processedHost = set $processedHost "port" (default 443 $host.port) }}
{{- if $host.rateLimit }}
{{- $processedHost = set $processedHost "rateLimit" $host.rateLimit }}
{{- end }}
{{- $processedHost = set $processedHost "preferred" (default false $host.preferred) }}
{{- if $processedHost.preferred }}
{{- $preferredHosts = append $preferredHosts $processedHost }}
{{- else }}
{{- $regularHosts = append $regularHosts $processedHost }}
{{- end }}
{{- end }}

{{- /* Combine all hosts with preferred ones first */ -}}
{{- $allHosts = concat $preferredHosts $regularHosts }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.fullname" . }}-photon-gateway-config
  labels:
    app.kubernetes.io/component: "photon-gateway"
    {{- include "common.labels" . | nindent 4 }}
data:
  envoy.yaml: |
    static_resources:
      listeners:
      - name: listener_0
        address:
          socket_address:
            protocol: TCP
            address: 0.0.0.0
            port_value: 8080
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: ingress_http
              access_log:
              - name: envoy.access_loggers.stdout
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
              http_filters:
              - name: envoy.filters.http.lua
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
                  inline_code: |
                    local cjson = require "cjson"
                    
                    function envoy_on_response(response_handle)
                      local status = response_handle:headers():get(":status")
                      
                      -- Only check 200 responses for content validity
                      if status ~= "200" then
                        return
                      end
                      
                      -- Check if we got a valid response with geocoding results
                      local body = response_handle:body()
                      
                      if body and body:length() > 0 then
                        local success, parsed = pcall(function()
                          local body_str = tostring(body:getBytes(0, body:length()))
                          return cjson.decode(body_str)
                        end)
                        
                        -- If parsing failed or no features, mark as retriable
                        if not success or not parsed or parsed.type ~= "FeatureCollection" then
                          response_handle:headers():add("x-photon-retry", "parse-error")
                          return
                        end
                        
                        -- If features array is empty, mark as retriable
                        if not parsed.features or type(parsed.features) ~= "table" or #parsed.features == 0 then
                          response_handle:headers():add("x-photon-retry", "no-results")
                          return
                        end
                      else
                        -- Empty body, mark as retriable
                        response_handle:headers():add("x-photon-retry", "empty-body")
                      end
                    end
              - name: envoy.filters.http.router
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
              route_config:
                name: local_route
                virtual_hosts:
                - name: local_service
                  domains: ["*"]
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      weighted_clusters:
                        clusters:
                        {{- range $index, $host := $allHosts }}
                        - name: photon_host_{{ add $index 1 }}
                          weight: {{ if $host.preferred }}100{{ else }}10{{ end }}
                        {{- end }}
                      timeout: 30s
                      retry_policy:
                        retry_on: 5xx,gateway-error,connect-failure,refused-stream,retriable-headers
                        retriable_headers:
                        - name: "x-photon-retry"
                        num_retries: {{ len $allHosts }}
                        per_try_timeout: 10s
                        retry_back_off:
                          base_interval: 0.1s
                          max_interval: 1s
      clusters:
      {{- range $index, $host := $allHosts }}
      - name: photon_host_{{ add $index 1 }}
        connect_timeout: 10s
        per_connection_buffer_limit_bytes: 32768
        type: STRICT_DNS
        dns_lookup_family: V4_PREFERRED
        lb_policy: ROUND_ROBIN
        max_requests_per_connection: 100
        upstream_connection_options:
          tcp_keepalive:
            keepalive_probes: 3
            keepalive_time: 30
            keepalive_interval: 5
        circuit_breakers:
          thresholds:
          - priority: DEFAULT
            max_connections: {{ if $host.preferred }}50{{ else }}20{{ end }}
            max_pending_requests: {{ if $host.preferred }}50{{ else }}20{{ end }}
            max_requests: {{ if $host.preferred }}100{{ else }}50{{ end }}
            max_retries: 3
        outlier_detection:
          consecutive_5xx: 3
          consecutive_gateway_failure: 3
          interval: 30s
          base_ejection_time: 30s
          max_ejection_percent: 50
          split_external_local_origin_errors: true
        {{- if and (not $host.internal) (eq $host.scheme "https") }}
        transport_socket:
          name: envoy.transport_sockets.tls
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
            sni: {{ $host.host }}
            auto_sni: true
            common_tls_context:
              validation_context:
                match_typed_subject_alt_names:
                - san_type: DNS
                  matcher:
                    exact: {{ $host.host }}
                trusted_ca:
                  filename: /etc/ssl/certs/ca-certificates.crt
        {{- end }}
        load_assignment:
          cluster_name: photon_host_{{ add $index 1 }}
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: {{ $host.host }}
                    port_value: {{ $host.port }}
        health_checks:
        {{- if $host.internal }}
        - timeout: {{ if $host.preferred }}3s{{ else }}5s{{ end }}
          interval: {{ if $host.preferred }}15s{{ else }}30s{{ end }}
          unhealthy_threshold: 3
          healthy_threshold: 2
          tcp_health_check: {}
        - timeout: {{ if $host.preferred }}5s{{ else }}10s{{ end }}
          interval: {{ if $host.preferred }}30s{{ else }}60s{{ end }}
          unhealthy_threshold: 3
          healthy_threshold: 2
          http_health_check:
            path: /api
            expected_statuses:
            - start: 200
              end: 299
            - start: 400
              end: 499
        {{- else }}
        - timeout: {{ if $host.preferred }}3s{{ else }}10s{{ end }}
          interval: {{ if $host.preferred }}15s{{ else }}60s{{ end }}
          unhealthy_threshold: 3
          healthy_threshold: 2
          http_health_check:
            path: /api
            expected_statuses:
            - start: 200
              end: 299
            - start: 400
              end: 499
        {{- end }}
      {{- end }}
{{- end }}