{{- if .Values.photon.enabled }}
{{- $allHosts := list }}
{{- $photonHosts := list }}

{{- /* Add internal photon host if deployed */ -}}
{{- if .Values.photon.deploy }}
{{- $internalHost := dict "host" (printf "%s-photon" (include "common.fullname" .)) "port" 2322 }}
{{- $photonHosts = append $photonHosts $internalHost }}
{{- end }}

{{- /* Add external hosts */ -}}
{{- range $host := .Values.photon.gateway.hosts }}
{{- $processedHost := dict "host" $host.host "port" (default 443 $host.port) }}
{{- $photonHosts = append $photonHosts $processedHost }}
{{- end }}

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "common.fullname" . }}-photon-gateway
  labels:
    app.kubernetes.io/component: "photon-gateway"
    {{- include "common.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: "photon-gateway"
      {{- include "common.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/component: "app"
          {{- include "common.selectorLabels" . | nindent 10 }}
    ports:
    - protocol: TCP
      port: 8080
  egress:
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  # Allow access to configured Photon hosts
  {{- range $host := $photonHosts }}
  - to: []
    ports:
    - protocol: TCP
      port: {{ $host.port }}
    {{- if $host.host }}
    # Host: {{ $host.host }}
    {{- end }}
  {{- end }}
{{- end }}