{{- if .Values.photon.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.fullname" . }}-photon-gateway
  labels:
    app.kubernetes.io/component: "photon-gateway"
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app.kubernetes.io/component: "photon-gateway"
    {{- include "common.selectorLabels" . | nindent 4 }}
{{- end }}