{{- if .Values.photon.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.fullname" . }}-photon-gateway
  labels:
    {{- include "dawarich.photonGateway.podLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    {{- include "dawarich.photonGateway.selectorLabels" . | nindent 4 }}
{{- end }}