apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "common.fullname" . }}-init-secret-job
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    app.kubernetes.io/name: {{ template "common.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "adguard-init-secret-job"
    {{- include "common.labels" . | nindent 4 }}
automountServiceAccountToken: true
