apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "common.fullname" . }}-init-secret-job
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    {{- include "adguard.initSecretJob.objectLabels" . | nindent 4 }}
automountServiceAccountToken: true
