{{- if .Values.secretInit.primary.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.primary.secretName }}
  {{- with .Values.secretInit.primary.annotations }}
  annotations:
    {{ . | toYaml | nindent 4 }}
  {{- end }}
{{- end }}
