{{- if not .Values.app.secretKeyBase.existingSecret }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "common.fullname" . }}-init-secret-job
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    {{- include "dawarich.secretInit.objectLabels" . | nindent 4 }}
{{- end }}
