apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    app.kubernetes.io/component: "generic-device-plugin"
    {{- include "common.labels" . | nindent 4 }}
data:
  config.yaml: |
    devices: {{ .Values.devices | toYaml | nindent 4 }}
