apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}
  labels: {{- include "genericDevicePlugin.objectLabels" . | nindent 4 }}
data:
  config.yaml: |
    devices: {{ .Values.devices | toYaml | nindent 4 }}
