kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ template "common.fullname" . }}
  labels:
    {{- include "dawarich.backend.objectLabels" . | nindent 4 }}
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      {{- include "dawarich.backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dawarich.backend.podLabels" . | nindent 8 }}
    spec:
      securityContext: {{ toYaml .Values.app.podSecurityContext | nindent 8 }}
      initContainers:
      - name: initialize-db
        image: '{{ .Values.app.image.registry }}/{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}'
        imagePullPolicy: {{ .Values.app.image.pullPolicy }}
        command: ["/bin/sh", "-c"]
        args:
        - cp -R /var/app/db/. /mnt/db/ && chmod -R g+rwX /mnt/db
        volumeMounts:
        - name: db
          mountPath: /mnt/db
      containers:
      - name: {{ .Chart.Name }}
        image: '{{ .Values.app.image.registry }}/{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}'
        imagePullPolicy: {{ .Values.app.image.pullPolicy }}
        securityContext: {{ toYaml .Values.app.securityContext | nindent 10 }}
        command: ['web-entrypoint.sh']
        args: ['bin/rails', 'server', '-p', '3000', '-b', '::']
        env:
          {{- include "dawarich.env" . | nindent 8 }}
        startupProbe:
          httpGet:
            port: http
            path: /api/v1/health
            httpHeaders:
            - name: Host
              value: {{ template "common.fullname" . }}
        livenessProbe:
          httpGet:
            port: http
            path: /api/v1/health
            httpHeaders:
            - name: Host
              value: {{ template "common.fullname" . }}
        readinessProbe:
          httpGet:
            port: http
            path: /api/v1/health
            httpHeaders:
            - name: Host
              value: {{ template "common.fullname" . }}
        volumeMounts:
        - name: data
          mountPath: /var/app/storage
        - name: db
          mountPath: /var/app/db
        - name: public
          mountPath: /var/app/public
        - name: tmp
          mountPath: /var/app/tmp
        - name: system-tmp
          mountPath: /tmp
        - name: log
          mountPath: /var/app/log
        ports:
        - name: http
          containerPort: 3000
        resources: {{ toYaml .Values.app.resources | nindent 12 }}
      - name: {{ .Chart.Name }}-sidekiq
        image: '{{ .Values.app.image.registry }}/{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}'
        imagePullPolicy: {{ .Values.app.image.pullPolicy }}
        securityContext: {{ toYaml .Values.app.securityContext | nindent 10 }}
        command: ['sidekiq-entrypoint.sh']
        args: ['bundle', 'exec', 'sidekiq']
        env:
          {{- include "dawarich.env" . | nindent 8 }}
        startupProbe:
          exec:
            command: [ "sh", "-c", "pgrep -f sidekiq" ]
        livenessProbe:
          exec:
            command: [ "sh", "-c", "pgrep -f sidekiq" ]
        readinessProbe:
          exec:
            command: [ "sh", "-c", "pgrep -f sidekiq" ]
        volumeMounts:
        - name: data
          mountPath: /var/app/storage
        - name: db
          mountPath: /var/app/db
        - name: tmp
          mountPath: /var/app/tmp
        - name: system-tmp
          mountPath: /tmp
        - name: log
          mountPath: /var/app/log
      volumes:
      - name: data
        emptyDir: {}
      - name: db
        emptyDir: {}
      - name: public
        emptyDir: {}
      - name: tmp
        emptyDir: {}
      - name: system-tmp
        emptyDir: {}
      - name: log
        emptyDir: {}
