apiVersion: v2
name: immich
version: 5.1.1

home: https://immich.app
sources:
- https://github.com/immich-app/immich

dependencies:
  - name: redis
    version: 21.1.11
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
