apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "common.fullname" . }}-role
  labels:
    {{- include "common.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "common.fullname" . }}-role-binding
  labels:
    {{- include "common.labels" . | nindent 4 }}
roleRef:
  kind: Role
  name: {{ template "common.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ template "common.fullname" . }}
  namespace: {{ .Release.Namespace }}
