image:
  registry: ghcr.io
  repository: home-assistant/home-assistant
  tag: 2024.8.1

nodeName:
tolerations: []

resources: {}

podSecurityContext: {}

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: [ "ALL" ]
    add: ["NET_RAW", "NET_BIND_SERVICE"]

persistence:
  size: 500Mi
  labels: {}

ingress:
  enabled: true
  domain: home.example.com
  class:
  annotations: {}
  tls:
    enabled: true
    secretName:

config:
  image:
    registry: ghcr.io
    repository: kiwigrid/k8s-sidecar
    tag: 1.27.5

  resources: {}

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: [ "ALL" ]
      add: []
