image:
  registry: ghcr.io
  repository: home-assistant/home-assistant
  tag: 2025.7.1

nodeName:
tolerations:

resources: {}

podSecurityContext: {}

securityContext:
  allowPrivilegeEscalation: false
  capabilities: {}

useHostNetworking: false

persistence:
  size: 500Mi
  labels: {}

route:
  enabled: false
  apiVersion: gateway.networking.k8s.io/v1
  kind: HTTPRoute
  annotations: {}
  hostnames:
    - home.example.com
  parentRefs: []
  filters: []
  matches: []

ingress:
  enabled: true
  domain: home.example.com
  class:
  annotations: {}
  tls:
    enabled: true
    secretName:

config:
  image:
    registry: ghcr.io
    repository: kiwigrid/k8s-sidecar
    tag: 1.30.7

  resources: {}

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: [ "ALL" ]
      add:

