apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: app
  labels:
    app.kubernetes.io/component: "db"
    {{- include "component.labels" (dict "componentName" "postgresql" "imageTag" .Values.database.image.tag "ctx" .) | nindent 4 }}
spec:
  name: app
  owner: app
  cluster:
    name: {{ .Values.database.clusterName }}
  extensions:
  - name: postgis
    ensure: present
