apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: app
  labels:
    {{- include "dawarich.database.podLabels" . | nindent 4 }}
spec:
  name: app
  owner: app
  cluster:
    name: {{ .Values.database.clusterName }}
  extensions:
  - name: postgis
    ensure: present
